# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'analogpremis.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(342, 365)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(10, 10, 324, 340))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.analogevent_type = QtWidgets.QComboBox(self.widget)
        self.analogevent_type.setObjectName("analogevent_type")
        self.analogevent_type.addItem("")
        self.analogevent_type.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.analogevent_type)
        self.verticalLayout.addLayout(self.formLayout)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.analogevent_date = QtWidgets.QLineEdit(self.widget)
        self.analogevent_date.setText("")
        self.analogevent_date.setObjectName("analogevent_date")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.analogevent_date)
        self.verticalLayout.addLayout(self.formLayout_3)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.analogevent_details = QtWidgets.QPlainTextEdit(self.widget)
        self.analogevent_details.setObjectName("analogevent_details")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.analogevent_details)
        self.verticalLayout.addLayout(self.formLayout_4)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.analogevent_agent = QtWidgets.QComboBox(self.widget)
        self.analogevent_agent.setObjectName("analogevent_agent")
        self.analogevent_agent.addItem("")
        self.analogevent_agent.addItem("")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.analogevent_agent)
        self.verticalLayout.addLayout(self.formLayout_5)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.widget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.buttonBox.raise_()
        self.label_2.raise_()
        self.analogevent_date.raise_()
        self.analogevent_details.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.analogevent_type.raise_()
        self.label_5.raise_()
        self.analogevent_agent.raise_()
        self.analogevent_details.raise_()
        self.analogevent_agent.raise_()
        self.analogevent_details.raise_()

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_4.setText(_translate("Dialog", "Event type:"))
        self.analogevent_type.setItemText(0, _translate("Dialog", "Physical repair"))
        self.analogevent_type.setItemText(1, _translate("Dialog", "Rehousing"))
        self.label_2.setText(_translate("Dialog", "Date:"))
        self.label_3.setText(_translate("Dialog", "Details:"))
        self.label_5.setText(_translate("Dialog", "Agent:"))
        self.analogevent_agent.setItemText(0, _translate("Dialog", "Andrec, Michael"))
        self.analogevent_agent.setItemText(1, _translate("Dialog", "Doe, John"))

