# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1066, 740)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 1001, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.resourceIdForm = QtWidgets.QFormLayout()
        self.resourceIdForm.setContentsMargins(11, 11, 11, 11)
        self.resourceIdForm.setSpacing(6)
        self.resourceIdForm.setObjectName("resourceIdForm")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setMinimumSize(QtCore.QSize(59, 0))
        self.label.setObjectName("label")
        self.resourceIdForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.resource_id = QtWidgets.QLineEdit(self.layoutWidget)
        self.resource_id.setMinimumSize(QtCore.QSize(200, 0))
        self.resource_id.setObjectName("resource_id")
        self.resourceIdForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.resource_id)
        self.horizontalLayout.addLayout(self.resourceIdForm)
        self.resourceTitleForm = QtWidgets.QFormLayout()
        self.resourceTitleForm.setContentsMargins(11, 11, 11, 11)
        self.resourceTitleForm.setSpacing(6)
        self.resourceTitleForm.setObjectName("resourceTitleForm")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(59, 0))
        self.label_2.setObjectName("label_2")
        self.resourceTitleForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.resource_title = QtWidgets.QLineEdit(self.layoutWidget)
        self.resource_title.setMinimumSize(QtCore.QSize(200, 0))
        self.resource_title.setObjectName("resource_title")
        self.resourceTitleForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.resource_title)
        self.horizontalLayout.addLayout(self.resourceTitleForm)
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(290, 50, 381, 621))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 30, 361, 581))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_10.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_10.setSpacing(6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.analog_id = QtWidgets.QLineEdit(self.layoutWidget1)
        self.analog_id.setObjectName("analog_id")
        self.verticalLayout_3.addWidget(self.analog_id)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.analog_source = QtWidgets.QLineEdit(self.layoutWidget1)
        self.analog_source.setObjectName("analog_source")
        self.verticalLayout_6.addWidget(self.analog_source)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.verticalLayout_10.addLayout(self.horizontalLayout_5)
        self.tape_type = QtWidgets.QComboBox(self.layoutWidget1)
        self.tape_type.setObjectName("tape_type")
        self.tape_type.addItem("")
        self.tape_type.addItem("")
        self.tape_type.addItem("")
        self.verticalLayout_10.addWidget(self.tape_type)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.analog_location = QtWidgets.QLineEdit(self.layoutWidget1)
        self.analog_location.setObjectName("analog_location")
        self.verticalLayout_7.addWidget(self.analog_location)
        self.horizontalLayout_6.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_8.addWidget(self.label_9)
        self.analog_date = QtWidgets.QLineEdit(self.layoutWidget1)
        self.analog_date.setObjectName("analog_date")
        self.verticalLayout_8.addWidget(self.analog_date)
        self.horizontalLayout_6.addLayout(self.verticalLayout_8)
        self.verticalLayout_10.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.analog_generation = QtWidgets.QComboBox(self.layoutWidget1)
        self.analog_generation.setObjectName("analog_generation")
        self.analog_generation.addItem("")
        self.analog_generation.addItem("")
        self.horizontalLayout_7.addWidget(self.analog_generation)
        self.analog_tapespeed = QtWidgets.QComboBox(self.layoutWidget1)
        self.analog_tapespeed.setObjectName("analog_tapespeed")
        self.analog_tapespeed.addItem("")
        self.analog_tapespeed.addItem("")
        self.analog_tapespeed.addItem("")
        self.analog_tapespeed.addItem("")
        self.analog_tapespeed.addItem("")
        self.analog_tapespeed.setItemText(4, "")
        self.horizontalLayout_7.addWidget(self.analog_tapespeed)
        self.verticalLayout_10.addLayout(self.horizontalLayout_7)
        self.analog_tracklayout = QtWidgets.QComboBox(self.layoutWidget1)
        self.analog_tracklayout.setObjectName("analog_tracklayout")
        self.analog_tracklayout.addItem("")
        self.analog_tracklayout.addItem("")
        self.analog_tracklayout.addItem("")
        self.analog_tracklayout.addItem("")
        self.analog_tracklayout.addItem("")
        self.analog_tracklayout.addItem("")
        self.analog_tracklayout.setItemText(5, "")
        self.verticalLayout_10.addWidget(self.analog_tracklayout)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_9.addWidget(self.label_10)
        self.analog_premis_list = QtWidgets.QListWidget(self.layoutWidget1)
        self.analog_premis_list.setObjectName("analog_premis_list")
        self.verticalLayout_9.addWidget(self.analog_premis_list)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.analogpremis_plusbutton = QtWidgets.QPushButton(self.layoutWidget1)
        self.analogpremis_plusbutton.setObjectName("analogpremis_plusbutton")
        self.horizontalLayout_8.addWidget(self.analogpremis_plusbutton)
        self.analogpremis_minusbutton = QtWidgets.QPushButton(self.layoutWidget1)
        self.analogpremis_minusbutton.setEnabled(False)
        self.analogpremis_minusbutton.setObjectName("analogpremis_minusbutton")
        self.horizontalLayout_8.addWidget(self.analogpremis_minusbutton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.analogpremis_upbutton = QtWidgets.QPushButton(self.layoutWidget1)
        self.analogpremis_upbutton.setEnabled(False)
        self.analogpremis_upbutton.setObjectName("analogpremis_upbutton")
        self.horizontalLayout_8.addWidget(self.analogpremis_upbutton)
        self.analogpremis_downbutton = QtWidgets.QPushButton(self.layoutWidget1)
        self.analogpremis_downbutton.setEnabled(False)
        self.analogpremis_downbutton.setObjectName("analogpremis_downbutton")
        self.horizontalLayout_8.addWidget(self.analogpremis_downbutton)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setGeometry(QtCore.QRect(680, 50, 381, 621))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget_7 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_7.setGeometry(QtCore.QRect(10, 30, 361, 581))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.layoutWidget_7)
        self.verticalLayout_11.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_11.setSpacing(6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_16.setSpacing(6)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.digitalinstantiation_list = QtWidgets.QListWidget(self.layoutWidget_7)
        self.digitalinstantiation_list.setObjectName("digitalinstantiation_list")
        self.verticalLayout_16.addWidget(self.digitalinstantiation_list)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.digitalinstantiation_plusbutton = QtWidgets.QPushButton(self.layoutWidget_7)
        self.digitalinstantiation_plusbutton.setObjectName("digitalinstantiation_plusbutton")
        self.horizontalLayout_12.addWidget(self.digitalinstantiation_plusbutton)
        self.digitalinstantiation_minusbutton = QtWidgets.QPushButton(self.layoutWidget_7)
        self.digitalinstantiation_minusbutton.setEnabled(False)
        self.digitalinstantiation_minusbutton.setObjectName("digitalinstantiation_minusbutton")
        self.horizontalLayout_12.addWidget(self.digitalinstantiation_minusbutton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem1)
        self.digitalinstantiation_upbutton = QtWidgets.QPushButton(self.layoutWidget_7)
        self.digitalinstantiation_upbutton.setEnabled(False)
        self.digitalinstantiation_upbutton.setObjectName("digitalinstantiation_upbutton")
        self.horizontalLayout_12.addWidget(self.digitalinstantiation_upbutton)
        self.digitalinstantiation_downbutton = QtWidgets.QPushButton(self.layoutWidget_7)
        self.digitalinstantiation_downbutton.setEnabled(False)
        self.digitalinstantiation_downbutton.setObjectName("digitalinstantiation_downbutton")
        self.horizontalLayout_12.addWidget(self.digitalinstantiation_downbutton)
        self.verticalLayout_16.addLayout(self.horizontalLayout_12)
        self.verticalLayout_11.addLayout(self.verticalLayout_16)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 50, 266, 621))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.description_list = QtWidgets.QListWidget(self.layoutWidget2)
        self.description_list.setObjectName("description_list")
        self.verticalLayout.addWidget(self.description_list)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.descriptionlist_plusbutton = QtWidgets.QPushButton(self.layoutWidget2)
        self.descriptionlist_plusbutton.setEnabled(True)
        self.descriptionlist_plusbutton.setObjectName("descriptionlist_plusbutton")
        self.horizontalLayout_2.addWidget(self.descriptionlist_plusbutton)
        self.descriptionlist_minusbutton = QtWidgets.QPushButton(self.layoutWidget2)
        self.descriptionlist_minusbutton.setEnabled(False)
        self.descriptionlist_minusbutton.setObjectName("descriptionlist_minusbutton")
        self.horizontalLayout_2.addWidget(self.descriptionlist_minusbutton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.descriptionlist_upbutton = QtWidgets.QPushButton(self.layoutWidget2)
        self.descriptionlist_upbutton.setEnabled(False)
        self.descriptionlist_upbutton.setObjectName("descriptionlist_upbutton")
        self.horizontalLayout_2.addWidget(self.descriptionlist_upbutton)
        self.descriptionlist_downbutton = QtWidgets.QPushButton(self.layoutWidget2)
        self.descriptionlist_downbutton.setEnabled(False)
        self.descriptionlist_downbutton.setObjectName("descriptionlist_downbutton")
        self.horizontalLayout_2.addWidget(self.descriptionlist_downbutton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.contributor_list = QtWidgets.QListWidget(self.layoutWidget2)
        self.contributor_list.setObjectName("contributor_list")
        self.verticalLayout_4.addWidget(self.contributor_list)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.contributorlist_plusbutton = QtWidgets.QPushButton(self.layoutWidget2)
        self.contributorlist_plusbutton.setObjectName("contributorlist_plusbutton")
        self.horizontalLayout_3.addWidget(self.contributorlist_plusbutton)
        self.contributorlist_minusbutton = QtWidgets.QPushButton(self.layoutWidget2)
        self.contributorlist_minusbutton.setEnabled(False)
        self.contributorlist_minusbutton.setObjectName("contributorlist_minusbutton")
        self.horizontalLayout_3.addWidget(self.contributorlist_minusbutton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.contributorlist_upbutton = QtWidgets.QPushButton(self.layoutWidget2)
        self.contributorlist_upbutton.setEnabled(False)
        self.contributorlist_upbutton.setObjectName("contributorlist_upbutton")
        self.horizontalLayout_3.addWidget(self.contributorlist_upbutton)
        self.contributorlist_downbutton = QtWidgets.QPushButton(self.layoutWidget2)
        self.contributorlist_downbutton.setEnabled(False)
        self.contributorlist_downbutton.setObjectName("contributorlist_downbutton")
        self.horizontalLayout_3.addWidget(self.contributorlist_downbutton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.language_list = QtWidgets.QListWidget(self.layoutWidget2)
        self.language_list.setObjectName("language_list")
        self.verticalLayout_5.addWidget(self.language_list)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.languagelist_plusbutton = QtWidgets.QPushButton(self.layoutWidget2)
        self.languagelist_plusbutton.setObjectName("languagelist_plusbutton")
        self.horizontalLayout_4.addWidget(self.languagelist_plusbutton)
        self.languagelist_minusbutton = QtWidgets.QPushButton(self.layoutWidget2)
        self.languagelist_minusbutton.setEnabled(False)
        self.languagelist_minusbutton.setObjectName("languagelist_minusbutton")
        self.horizontalLayout_4.addWidget(self.languagelist_minusbutton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.languagelist_upbutton = QtWidgets.QPushButton(self.layoutWidget2)
        self.languagelist_upbutton.setEnabled(False)
        self.languagelist_upbutton.setObjectName("languagelist_upbutton")
        self.horizontalLayout_4.addWidget(self.languagelist_upbutton)
        self.languagelist_downbutton = QtWidgets.QPushButton(self.layoutWidget2)
        self.languagelist_downbutton.setEnabled(False)
        self.languagelist_downbutton.setObjectName("languagelist_downbutton")
        self.horizontalLayout_4.addWidget(self.languagelist_downbutton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addLayout(self.verticalLayout_5)
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.groupBox.raise_()
        self.groupBox_2.raise_()
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1066, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionBlow_away = QtWidgets.QAction(MainWindow)
        self.actionBlow_away.setObjectName("actionBlow_away")
        self.actionFoot = QtWidgets.QAction(MainWindow)
        self.actionFoot.setObjectName("actionFoot")
        self.actionHead = QtWidgets.QAction(MainWindow)
        self.actionHead.setObjectName("actionHead")
        self.actionFingers = QtWidgets.QAction(MainWindow)
        self.actionFingers.setObjectName("actionFingers")
        self.actionFoo = QtWidgets.QAction(MainWindow)
        self.actionFoo.setObjectName("actionFoo")
        self.actionBar = QtWidgets.QAction(MainWindow)
        self.actionBar.setObjectName("actionBar")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PBCore Editor"))
        self.label.setText(_translate("MainWindow", "Resource ID:"))
        self.label_2.setText(_translate("MainWindow", "Resource Title:"))
        self.groupBox.setTitle(_translate("MainWindow", "Analog instantiation"))
        self.label_4.setText(_translate("MainWindow", "Identifier:"))
        self.label_5.setText(_translate("MainWindow", "Source:"))
        self.tape_type.setItemText(0, _translate("MainWindow", "1/4\" audio tape"))
        self.tape_type.setItemText(1, _translate("MainWindow", "Cassette tape"))
        self.tape_type.setItemText(2, _translate("MainWindow", "Microcassette"))
        self.label_8.setText(_translate("MainWindow", "Location:"))
        self.label_9.setText(_translate("MainWindow", "Date:"))
        self.analog_generation.setItemText(0, _translate("MainWindow", "Original"))
        self.analog_generation.setItemText(1, _translate("MainWindow", "Copy"))
        self.analog_tapespeed.setItemText(0, _translate("MainWindow", "7.5 ips"))
        self.analog_tapespeed.setItemText(1, _translate("MainWindow", "3.75 ips"))
        self.analog_tapespeed.setItemText(2, _translate("MainWindow", "1.875 ips"))
        self.analog_tapespeed.setItemText(3, _translate("MainWindow", "15 ips"))
        self.analog_tracklayout.setItemText(0, _translate("MainWindow", "Half-track stereo"))
        self.analog_tracklayout.setItemText(1, _translate("MainWindow", "Half-track mono"))
        self.analog_tracklayout.setItemText(2, _translate("MainWindow", "Full-track mono"))
        self.analog_tracklayout.setItemText(3, _translate("MainWindow", "Quarter-track stereo"))
        self.analog_tracklayout.setItemText(4, _translate("MainWindow", "Four-track"))
        self.label_10.setText(_translate("MainWindow", "Analog instantiation PREMIS event(s):"))
        self.analogpremis_plusbutton.setText(_translate("MainWindow", "+"))
        self.analogpremis_minusbutton.setText(_translate("MainWindow", "–"))
        self.analogpremis_upbutton.setText(_translate("MainWindow", "↑"))
        self.analogpremis_downbutton.setText(_translate("MainWindow", "↓"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Digital instantiations"))
        self.digitalinstantiation_plusbutton.setText(_translate("MainWindow", "+"))
        self.digitalinstantiation_minusbutton.setText(_translate("MainWindow", "–"))
        self.digitalinstantiation_upbutton.setText(_translate("MainWindow", "↑"))
        self.digitalinstantiation_downbutton.setText(_translate("MainWindow", "↓"))
        self.label_3.setText(_translate("MainWindow", "Description(s):"))
        self.descriptionlist_plusbutton.setText(_translate("MainWindow", "+"))
        self.descriptionlist_minusbutton.setText(_translate("MainWindow", "–"))
        self.descriptionlist_upbutton.setText(_translate("MainWindow", "↑"))
        self.descriptionlist_downbutton.setText(_translate("MainWindow", "↓"))
        self.label_6.setText(_translate("MainWindow", "Contributor(s):"))
        self.contributorlist_plusbutton.setText(_translate("MainWindow", "+"))
        self.contributorlist_minusbutton.setText(_translate("MainWindow", "–"))
        self.contributorlist_upbutton.setText(_translate("MainWindow", "↑"))
        self.contributorlist_downbutton.setText(_translate("MainWindow", "↓"))
        self.label_7.setText(_translate("MainWindow", "Language(s):"))
        self.languagelist_plusbutton.setText(_translate("MainWindow", "+"))
        self.languagelist_minusbutton.setText(_translate("MainWindow", "–"))
        self.languagelist_upbutton.setText(_translate("MainWindow", "↑"))
        self.languagelist_downbutton.setText(_translate("MainWindow", "↓"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionNew.setText(_translate("MainWindow", "New..."))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as..."))
        self.actionBlow_away.setText(_translate("MainWindow", "Blow away..."))
        self.actionFoot.setText(_translate("MainWindow", "Foot"))
        self.actionHead.setText(_translate("MainWindow", "Head"))
        self.actionFingers.setText(_translate("MainWindow", "Fingers"))
        self.actionFoo.setText(_translate("MainWindow", "Foo"))
        self.actionBar.setText(_translate("MainWindow", "Bar"))

