# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(740, 740)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 20, 731, 661))
        self.tabWidget.setObjectName("tabWidget")
        self.descMD = QtWidgets.QWidget()
        self.descMD.setObjectName("descMD")
        self.layoutWidget = QtWidgets.QWidget(self.descMD)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 490, 338, 131))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.language_list = QtWidgets.QListWidget(self.layoutWidget)
        self.language_list.setObjectName("language_list")
        self.verticalLayout_5.addWidget(self.language_list)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.toolButton_6 = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton_6.setObjectName("toolButton_6")
        self.horizontalLayout_4.addWidget(self.toolButton_6)
        self.toolButton_5 = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton_5.setObjectName("toolButton_5")
        self.horizontalLayout_4.addWidget(self.toolButton_5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.languagelist_upbutton = QtWidgets.QPushButton(self.layoutWidget)
        self.languagelist_upbutton.setEnabled(False)
        self.languagelist_upbutton.setObjectName("languagelist_upbutton")
        self.horizontalLayout_4.addWidget(self.languagelist_upbutton)
        self.languagelist_downbutton = QtWidgets.QPushButton(self.layoutWidget)
        self.languagelist_downbutton.setEnabled(False)
        self.languagelist_downbutton.setObjectName("languagelist_downbutton")
        self.horizontalLayout_4.addWidget(self.languagelist_downbutton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.layoutWidget1 = QtWidgets.QWidget(self.descMD)
        self.layoutWidget1.setGeometry(QtCore.QRect(380, 200, 341, 231))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.description_list = QtWidgets.QListWidget(self.layoutWidget1)
        self.description_list.setObjectName("description_list")
        self.verticalLayout.addWidget(self.description_list)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.desc_addbutton = QtWidgets.QToolButton(self.layoutWidget1)
        self.desc_addbutton.setObjectName("desc_addbutton")
        self.horizontalLayout_2.addWidget(self.desc_addbutton)
        self.desc_removebutton = QtWidgets.QToolButton(self.layoutWidget1)
        self.desc_removebutton.setObjectName("desc_removebutton")
        self.horizontalLayout_2.addWidget(self.desc_removebutton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.desc_upbutton = QtWidgets.QPushButton(self.layoutWidget1)
        self.desc_upbutton.setEnabled(False)
        self.desc_upbutton.setObjectName("desc_upbutton")
        self.horizontalLayout_2.addWidget(self.desc_upbutton)
        self.desc_downbutton = QtWidgets.QPushButton(self.layoutWidget1)
        self.desc_downbutton.setEnabled(False)
        self.desc_downbutton.setObjectName("desc_downbutton")
        self.horizontalLayout_2.addWidget(self.desc_downbutton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.layoutWidget_2 = QtWidgets.QWidget(self.descMD)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 180, 338, 131))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_6.addWidget(self.label_11)
        self.contributor_list_2 = QtWidgets.QListWidget(self.layoutWidget_2)
        self.contributor_list_2.setObjectName("contributor_list_2")
        self.verticalLayout_6.addWidget(self.contributor_list_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.toolButton_11 = QtWidgets.QToolButton(self.layoutWidget_2)
        self.toolButton_11.setObjectName("toolButton_11")
        self.horizontalLayout_5.addWidget(self.toolButton_11)
        self.toolButton_12 = QtWidgets.QToolButton(self.layoutWidget_2)
        self.toolButton_12.setObjectName("toolButton_12")
        self.horizontalLayout_5.addWidget(self.toolButton_12)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.contributorlist_upbutton_2 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.contributorlist_upbutton_2.setEnabled(False)
        self.contributorlist_upbutton_2.setObjectName("contributorlist_upbutton_2")
        self.horizontalLayout_5.addWidget(self.contributorlist_upbutton_2)
        self.contributorlist_downbutton_2 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.contributorlist_downbutton_2.setEnabled(False)
        self.contributorlist_downbutton_2.setObjectName("contributorlist_downbutton_2")
        self.horizontalLayout_5.addWidget(self.contributorlist_downbutton_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.layoutWidget_3 = QtWidgets.QWidget(self.descMD)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 340, 338, 131))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_12.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_12.setSpacing(6)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_12.addWidget(self.label_12)
        self.contributor_list_3 = QtWidgets.QListWidget(self.layoutWidget_3)
        self.contributor_list_3.setObjectName("contributor_list_3")
        self.verticalLayout_12.addWidget(self.contributor_list_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.toolButton_13 = QtWidgets.QToolButton(self.layoutWidget_3)
        self.toolButton_13.setObjectName("toolButton_13")
        self.horizontalLayout_7.addWidget(self.toolButton_13)
        self.toolButton_14 = QtWidgets.QToolButton(self.layoutWidget_3)
        self.toolButton_14.setObjectName("toolButton_14")
        self.horizontalLayout_7.addWidget(self.toolButton_14)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.contributorlist_upbutton_3 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.contributorlist_upbutton_3.setEnabled(False)
        self.contributorlist_upbutton_3.setObjectName("contributorlist_upbutton_3")
        self.horizontalLayout_7.addWidget(self.contributorlist_upbutton_3)
        self.contributorlist_downbutton_3 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.contributorlist_downbutton_3.setEnabled(False)
        self.contributorlist_downbutton_3.setObjectName("contributorlist_downbutton_3")
        self.horizontalLayout_7.addWidget(self.contributorlist_downbutton_3)
        self.verticalLayout_12.addLayout(self.horizontalLayout_7)
        self.layoutWidget_4 = QtWidgets.QWidget(self.descMD)
        self.layoutWidget_4.setGeometry(QtCore.QRect(380, 440, 338, 131))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_13.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_13.setSpacing(6)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_13.addWidget(self.label_13)
        self.language_list_2 = QtWidgets.QListWidget(self.layoutWidget_4)
        self.language_list_2.setObjectName("language_list_2")
        self.verticalLayout_13.addWidget(self.language_list_2)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.toolButton_15 = QtWidgets.QToolButton(self.layoutWidget_4)
        self.toolButton_15.setObjectName("toolButton_15")
        self.horizontalLayout_9.addWidget(self.toolButton_15)
        self.toolButton_16 = QtWidgets.QToolButton(self.layoutWidget_4)
        self.toolButton_16.setObjectName("toolButton_16")
        self.horizontalLayout_9.addWidget(self.toolButton_16)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.languagelist_upbutton_2 = QtWidgets.QPushButton(self.layoutWidget_4)
        self.languagelist_upbutton_2.setEnabled(False)
        self.languagelist_upbutton_2.setObjectName("languagelist_upbutton_2")
        self.horizontalLayout_9.addWidget(self.languagelist_upbutton_2)
        self.languagelist_downbutton_2 = QtWidgets.QPushButton(self.layoutWidget_4)
        self.languagelist_downbutton_2.setEnabled(False)
        self.languagelist_downbutton_2.setObjectName("languagelist_downbutton_2")
        self.horizontalLayout_9.addWidget(self.languagelist_downbutton_2)
        self.verticalLayout_13.addLayout(self.horizontalLayout_9)
        self.widget = QtWidgets.QWidget(self.descMD)
        self.widget.setGeometry(QtCore.QRect(0, 14, 701, 131))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.identifier = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.identifier.sizePolicy().hasHeightForWidth())
        self.identifier.setSizePolicy(sizePolicy)
        self.identifier.setObjectName("identifier")
        self.verticalLayout_2.addWidget(self.identifier)
        self.identifier_2 = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.identifier_2.sizePolicy().hasHeightForWidth())
        self.identifier_2.setSizePolicy(sizePolicy)
        self.identifier_2.setSizeIncrement(QtCore.QSize(0, 10))
        self.identifier_2.setObjectName("identifier_2")
        self.verticalLayout_2.addWidget(self.identifier_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.asset_type = QtWidgets.QComboBox(self.widget)
        self.asset_type.setObjectName("asset_type")
        self.asset_type.addItem("")
        self.horizontalLayout.addWidget(self.asset_type)
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.identifier.raise_()
        self.asset_type.raise_()
        self.layoutWidget_2.raise_()
        self.layoutWidget_3.raise_()
        self.layoutWidget_4.raise_()
        self.tabWidget.addTab(self.descMD, "")
        self.rightsMD = QtWidgets.QWidget()
        self.rightsMD.setObjectName("rightsMD")
        self.layoutWidget_5 = QtWidgets.QWidget(self.rightsMD)
        self.layoutWidget_5.setGeometry(QtCore.QRect(20, 280, 338, 199))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.contributor_list = QtWidgets.QListWidget(self.layoutWidget_5)
        self.contributor_list.setObjectName("contributor_list")
        self.verticalLayout_4.addWidget(self.contributor_list)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.toolButton_4 = QtWidgets.QToolButton(self.layoutWidget_5)
        self.toolButton_4.setObjectName("toolButton_4")
        self.horizontalLayout_3.addWidget(self.toolButton_4)
        self.toolButton_3 = QtWidgets.QToolButton(self.layoutWidget_5)
        self.toolButton_3.setObjectName("toolButton_3")
        self.horizontalLayout_3.addWidget(self.toolButton_3)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.contributorlist_upbutton = QtWidgets.QPushButton(self.layoutWidget_5)
        self.contributorlist_upbutton.setEnabled(False)
        self.contributorlist_upbutton.setObjectName("contributorlist_upbutton")
        self.horizontalLayout_3.addWidget(self.contributorlist_upbutton)
        self.contributorlist_downbutton = QtWidgets.QPushButton(self.layoutWidget_5)
        self.contributorlist_downbutton.setEnabled(False)
        self.contributorlist_downbutton.setObjectName("contributorlist_downbutton")
        self.horizontalLayout_3.addWidget(self.contributorlist_downbutton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.layoutWidget_6 = QtWidgets.QWidget(self.rightsMD)
        self.layoutWidget_6.setGeometry(QtCore.QRect(20, 60, 338, 199))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.contributor_list_4 = QtWidgets.QListWidget(self.layoutWidget_6)
        self.contributor_list_4.setObjectName("contributor_list_4")
        self.verticalLayout_7.addWidget(self.contributor_list_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.toolButton_17 = QtWidgets.QToolButton(self.layoutWidget_6)
        self.toolButton_17.setObjectName("toolButton_17")
        self.horizontalLayout_6.addWidget(self.toolButton_17)
        self.toolButton_18 = QtWidgets.QToolButton(self.layoutWidget_6)
        self.toolButton_18.setObjectName("toolButton_18")
        self.horizontalLayout_6.addWidget(self.toolButton_18)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.contributorlist_upbutton_4 = QtWidgets.QPushButton(self.layoutWidget_6)
        self.contributorlist_upbutton_4.setEnabled(False)
        self.contributorlist_upbutton_4.setObjectName("contributorlist_upbutton_4")
        self.horizontalLayout_6.addWidget(self.contributorlist_upbutton_4)
        self.contributorlist_downbutton_4 = QtWidgets.QPushButton(self.layoutWidget_6)
        self.contributorlist_downbutton_4.setEnabled(False)
        self.contributorlist_downbutton_4.setObjectName("contributorlist_downbutton_4")
        self.horizontalLayout_6.addWidget(self.contributorlist_downbutton_4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.layoutWidget_8 = QtWidgets.QWidget(self.rightsMD)
        self.layoutWidget_8.setGeometry(QtCore.QRect(380, 60, 338, 199))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget_8)
        self.verticalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget_8)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_8.addWidget(self.label_9)
        self.contributor_list_5 = QtWidgets.QListWidget(self.layoutWidget_8)
        self.contributor_list_5.setObjectName("contributor_list_5")
        self.verticalLayout_8.addWidget(self.contributor_list_5)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.toolButton_19 = QtWidgets.QToolButton(self.layoutWidget_8)
        self.toolButton_19.setObjectName("toolButton_19")
        self.horizontalLayout_10.addWidget(self.toolButton_19)
        self.toolButton_20 = QtWidgets.QToolButton(self.layoutWidget_8)
        self.toolButton_20.setObjectName("toolButton_20")
        self.horizontalLayout_10.addWidget(self.toolButton_20)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem7)
        self.contributorlist_upbutton_5 = QtWidgets.QPushButton(self.layoutWidget_8)
        self.contributorlist_upbutton_5.setEnabled(False)
        self.contributorlist_upbutton_5.setObjectName("contributorlist_upbutton_5")
        self.horizontalLayout_10.addWidget(self.contributorlist_upbutton_5)
        self.contributorlist_downbutton_5 = QtWidgets.QPushButton(self.layoutWidget_8)
        self.contributorlist_downbutton_5.setEnabled(False)
        self.contributorlist_downbutton_5.setObjectName("contributorlist_downbutton_5")
        self.horizontalLayout_10.addWidget(self.contributorlist_downbutton_5)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        self.layoutWidget_9 = QtWidgets.QWidget(self.rightsMD)
        self.layoutWidget_9.setGeometry(QtCore.QRect(380, 280, 338, 199))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.layoutWidget_9)
        self.verticalLayout_14.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_14.setSpacing(6)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget_9)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_14.addWidget(self.label_14)
        self.contributor_list_6 = QtWidgets.QListWidget(self.layoutWidget_9)
        self.contributor_list_6.setObjectName("contributor_list_6")
        self.verticalLayout_14.addWidget(self.contributor_list_6)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.toolButton_21 = QtWidgets.QToolButton(self.layoutWidget_9)
        self.toolButton_21.setObjectName("toolButton_21")
        self.horizontalLayout_11.addWidget(self.toolButton_21)
        self.toolButton_22 = QtWidgets.QToolButton(self.layoutWidget_9)
        self.toolButton_22.setObjectName("toolButton_22")
        self.horizontalLayout_11.addWidget(self.toolButton_22)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem8)
        self.contributorlist_upbutton_6 = QtWidgets.QPushButton(self.layoutWidget_9)
        self.contributorlist_upbutton_6.setEnabled(False)
        self.contributorlist_upbutton_6.setObjectName("contributorlist_upbutton_6")
        self.horizontalLayout_11.addWidget(self.contributorlist_upbutton_6)
        self.contributorlist_downbutton_6 = QtWidgets.QPushButton(self.layoutWidget_9)
        self.contributorlist_downbutton_6.setEnabled(False)
        self.contributorlist_downbutton_6.setObjectName("contributorlist_downbutton_6")
        self.horizontalLayout_11.addWidget(self.contributorlist_downbutton_6)
        self.verticalLayout_14.addLayout(self.horizontalLayout_11)
        self.tabWidget.addTab(self.rightsMD, "")
        self.analogInst = QtWidgets.QWidget()
        self.analogInst.setObjectName("analogInst")
        self.tape_type = QtWidgets.QComboBox(self.analogInst)
        self.tape_type.setGeometry(QtCore.QRect(10, 120, 261, 31))
        self.tape_type.setObjectName("tape_type")
        self.tape_type.addItem("")
        self.tape_type.addItem("")
        self.tape_type.addItem("")
        self.analog_tracklayout = QtWidgets.QComboBox(self.analogInst)
        self.analog_tracklayout.setGeometry(QtCore.QRect(10, 220, 261, 31))
        self.analog_tracklayout.setObjectName("analog_tracklayout")
        self.analog_tracklayout.addItem("")
        self.analog_tracklayout.addItem("")
        self.analog_tracklayout.addItem("")
        self.analog_tracklayout.addItem("")
        self.analog_tracklayout.addItem("")
        self.analog_tracklayout.addItem("")
        self.analog_tracklayout.setItemText(5, "")
        self.layoutWidget2 = QtWidgets.QWidget(self.analogInst)
        self.layoutWidget2.setGeometry(QtCore.QRect(290, 20, 411, 601))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_10.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_10.setSpacing(6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_9.addWidget(self.label_10)
        self.analog_premis_list = QtWidgets.QListWidget(self.layoutWidget2)
        self.analog_premis_list.setObjectName("analog_premis_list")
        self.verticalLayout_9.addWidget(self.analog_premis_list)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.toolButton_8 = QtWidgets.QToolButton(self.layoutWidget2)
        self.toolButton_8.setObjectName("toolButton_8")
        self.horizontalLayout_8.addWidget(self.toolButton_8)
        self.toolButton_7 = QtWidgets.QToolButton(self.layoutWidget2)
        self.toolButton_7.setObjectName("toolButton_7")
        self.horizontalLayout_8.addWidget(self.toolButton_7)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.analogpremis_upbutton = QtWidgets.QPushButton(self.layoutWidget2)
        self.analogpremis_upbutton.setEnabled(False)
        self.analogpremis_upbutton.setObjectName("analogpremis_upbutton")
        self.horizontalLayout_8.addWidget(self.analogpremis_upbutton)
        self.analogpremis_downbutton = QtWidgets.QPushButton(self.layoutWidget2)
        self.analogpremis_downbutton.setEnabled(False)
        self.analogpremis_downbutton.setObjectName("analogpremis_downbutton")
        self.horizontalLayout_8.addWidget(self.analogpremis_downbutton)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.analog_generation = QtWidgets.QComboBox(self.analogInst)
        self.analog_generation.setGeometry(QtCore.QRect(10, 160, 261, 31))
        self.analog_generation.setObjectName("analog_generation")
        self.analog_generation.addItem("")
        self.analog_generation.addItem("")
        self.analog_generation.addItem("")
        self.analog_generation.setItemText(2, "")
        self.analog_tapespeed = QtWidgets.QComboBox(self.analogInst)
        self.analog_tapespeed.setGeometry(QtCore.QRect(10, 260, 261, 31))
        self.analog_tapespeed.setObjectName("analog_tapespeed")
        self.analog_tapespeed.addItem("")
        self.analog_tapespeed.addItem("")
        self.analog_tapespeed.addItem("")
        self.analog_tapespeed.addItem("")
        self.analog_tapespeed.addItem("")
        self.analog_tapespeed.setItemText(4, "")
        self.analog_tracklayout_2 = QtWidgets.QComboBox(self.analogInst)
        self.analog_tracklayout_2.setGeometry(QtCore.QRect(10, 340, 261, 31))
        self.analog_tracklayout_2.setObjectName("analog_tracklayout_2")
        self.analog_tracklayout_2.addItem("")
        self.analog_tracklayout_2.addItem("")
        self.analog_tracklayout_2.addItem("")
        self.analog_tracklayout_2.addItem("")
        self.analog_tracklayout_2.addItem("")
        self.analog_tracklayout_2.setItemText(4, "")
        self.analog_tracklayout_3 = QtWidgets.QComboBox(self.analogInst)
        self.analog_tracklayout_3.setGeometry(QtCore.QRect(10, 380, 261, 31))
        self.analog_tracklayout_3.setObjectName("analog_tracklayout_3")
        self.analog_tracklayout_3.addItem("")
        self.analog_tracklayout_3.addItem("")
        self.analog_tracklayout_3.addItem("")
        self.analog_tracklayout_3.addItem("")
        self.analog_tracklayout_3.setItemText(3, "")
        self.analog_tracklayout_4 = QtWidgets.QComboBox(self.analogInst)
        self.analog_tracklayout_4.setGeometry(QtCore.QRect(10, 420, 261, 31))
        self.analog_tracklayout_4.setObjectName("analog_tracklayout_4")
        self.analog_tracklayout_4.addItem("")
        self.analog_tracklayout_4.addItem("")
        self.analog_tracklayout_4.addItem("")
        self.analog_tracklayout_4.addItem("")
        self.analog_tracklayout_4.setItemText(3, "")
        self.tabWidget.addTab(self.analogInst, "")
        self.digitalInst = QtWidgets.QWidget()
        self.digitalInst.setObjectName("digitalInst")
        self.layoutWidget_7 = QtWidgets.QWidget(self.digitalInst)
        self.layoutWidget_7.setGeometry(QtCore.QRect(10, 20, 701, 601))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.layoutWidget_7)
        self.verticalLayout_11.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_11.setSpacing(6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_16.setSpacing(6)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.digitalinstantiation_list = QtWidgets.QListWidget(self.layoutWidget_7)
        self.digitalinstantiation_list.setObjectName("digitalinstantiation_list")
        self.verticalLayout_16.addWidget(self.digitalinstantiation_list)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.toolButton_10 = QtWidgets.QToolButton(self.layoutWidget_7)
        self.toolButton_10.setObjectName("toolButton_10")
        self.horizontalLayout_12.addWidget(self.toolButton_10)
        self.toolButton_9 = QtWidgets.QToolButton(self.layoutWidget_7)
        self.toolButton_9.setObjectName("toolButton_9")
        self.horizontalLayout_12.addWidget(self.toolButton_9)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem10)
        self.digitalinstantiation_upbutton = QtWidgets.QPushButton(self.layoutWidget_7)
        self.digitalinstantiation_upbutton.setEnabled(False)
        self.digitalinstantiation_upbutton.setObjectName("digitalinstantiation_upbutton")
        self.horizontalLayout_12.addWidget(self.digitalinstantiation_upbutton)
        self.digitalinstantiation_downbutton = QtWidgets.QPushButton(self.layoutWidget_7)
        self.digitalinstantiation_downbutton.setEnabled(False)
        self.digitalinstantiation_downbutton.setObjectName("digitalinstantiation_downbutton")
        self.horizontalLayout_12.addWidget(self.digitalinstantiation_downbutton)
        self.verticalLayout_16.addLayout(self.horizontalLayout_12)
        self.verticalLayout_11.addLayout(self.verticalLayout_16)
        self.tabWidget.addTab(self.digitalInst, "")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 740, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionBlow_away = QtWidgets.QAction(MainWindow)
        self.actionBlow_away.setObjectName("actionBlow_away")
        self.actionFoot = QtWidgets.QAction(MainWindow)
        self.actionFoot.setObjectName("actionFoot")
        self.actionHead = QtWidgets.QAction(MainWindow)
        self.actionHead.setObjectName("actionHead")
        self.actionFingers = QtWidgets.QAction(MainWindow)
        self.actionFingers.setObjectName("actionFingers")
        self.actionFoo = QtWidgets.QAction(MainWindow)
        self.actionFoo.setObjectName("actionFoo")
        self.actionBar = QtWidgets.QAction(MainWindow)
        self.actionBar.setObjectName("actionBar")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionClose)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PBCore Editor"))
        self.label_7.setText(_translate("MainWindow", "Language:"))
        self.toolButton_6.setText(_translate("MainWindow", "Add"))
        self.toolButton_5.setText(_translate("MainWindow", "Remove"))
        self.languagelist_upbutton.setText(_translate("MainWindow", "↑"))
        self.languagelist_downbutton.setText(_translate("MainWindow", "↓"))
        self.label_3.setText(_translate("MainWindow", "Description:"))
        self.desc_addbutton.setText(_translate("MainWindow", "Add"))
        self.desc_removebutton.setText(_translate("MainWindow", "Remove"))
        self.desc_upbutton.setText(_translate("MainWindow", "↑"))
        self.desc_downbutton.setText(_translate("MainWindow", "↓"))
        self.label_11.setText(_translate("MainWindow", "Title:"))
        self.toolButton_11.setText(_translate("MainWindow", "Add"))
        self.toolButton_12.setText(_translate("MainWindow", "Remove"))
        self.contributorlist_upbutton_2.setText(_translate("MainWindow", "↑"))
        self.contributorlist_downbutton_2.setText(_translate("MainWindow", "↓"))
        self.label_12.setText(_translate("MainWindow", "Date:"))
        self.toolButton_13.setText(_translate("MainWindow", "Add"))
        self.toolButton_14.setText(_translate("MainWindow", "Remove"))
        self.contributorlist_upbutton_3.setText(_translate("MainWindow", "↑"))
        self.contributorlist_downbutton_3.setText(_translate("MainWindow", "↓"))
        self.label_13.setText(_translate("MainWindow", "Coverage:"))
        self.toolButton_15.setText(_translate("MainWindow", "Add"))
        self.toolButton_16.setText(_translate("MainWindow", "Remove"))
        self.languagelist_upbutton_2.setText(_translate("MainWindow", "↑"))
        self.languagelist_downbutton_2.setText(_translate("MainWindow", "↓"))
        self.identifier.setPlaceholderText(_translate("MainWindow", "Identifier"))
        self.identifier_2.setPlaceholderText(_translate("MainWindow", "Location"))
        self.asset_type.setItemText(0, _translate("MainWindow", "Media Object"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.descMD), _translate("MainWindow", "Descriptive Metadata"))
        self.label_6.setText(_translate("MainWindow", "Contributor:"))
        self.toolButton_4.setText(_translate("MainWindow", "Add"))
        self.toolButton_3.setText(_translate("MainWindow", "Remove"))
        self.contributorlist_upbutton.setText(_translate("MainWindow", "↑"))
        self.contributorlist_downbutton.setText(_translate("MainWindow", "↓"))
        self.label_8.setText(_translate("MainWindow", "Creator:"))
        self.toolButton_17.setText(_translate("MainWindow", "Add"))
        self.toolButton_18.setText(_translate("MainWindow", "Remove"))
        self.contributorlist_upbutton_4.setText(_translate("MainWindow", "↑"))
        self.contributorlist_downbutton_4.setText(_translate("MainWindow", "↓"))
        self.label_9.setText(_translate("MainWindow", "Publisher:"))
        self.toolButton_19.setText(_translate("MainWindow", "Add"))
        self.toolButton_20.setText(_translate("MainWindow", "Remove"))
        self.contributorlist_upbutton_5.setText(_translate("MainWindow", "↑"))
        self.contributorlist_downbutton_5.setText(_translate("MainWindow", "↓"))
        self.label_14.setText(_translate("MainWindow", "Rights Summary:"))
        self.toolButton_21.setText(_translate("MainWindow", "Add"))
        self.toolButton_22.setText(_translate("MainWindow", "Remove"))
        self.contributorlist_upbutton_6.setText(_translate("MainWindow", "↑"))
        self.contributorlist_downbutton_6.setText(_translate("MainWindow", "↓"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.rightsMD), _translate("MainWindow", "Rights Metadata"))
        self.tape_type.setItemText(0, _translate("MainWindow", "1/4\" audio tape"))
        self.tape_type.setItemText(1, _translate("MainWindow", "Cassette tape"))
        self.tape_type.setItemText(2, _translate("MainWindow", "Microcassette"))
        self.analog_tracklayout.setItemText(0, _translate("MainWindow", "Half-track stereo"))
        self.analog_tracklayout.setItemText(1, _translate("MainWindow", "Half-track mono"))
        self.analog_tracklayout.setItemText(2, _translate("MainWindow", "Full-track mono"))
        self.analog_tracklayout.setItemText(3, _translate("MainWindow", "Quarter-track stereo"))
        self.analog_tracklayout.setItemText(4, _translate("MainWindow", "Four-track"))
        self.label_10.setText(_translate("MainWindow", "PREMIS event(s):"))
        self.toolButton_8.setText(_translate("MainWindow", "Add"))
        self.toolButton_7.setText(_translate("MainWindow", "Remove"))
        self.analogpremis_upbutton.setText(_translate("MainWindow", "↑"))
        self.analogpremis_downbutton.setText(_translate("MainWindow", "↓"))
        self.analog_generation.setItemText(0, _translate("MainWindow", "Original"))
        self.analog_generation.setItemText(1, _translate("MainWindow", "Copy"))
        self.analog_tapespeed.setItemText(0, _translate("MainWindow", "7.5 ips"))
        self.analog_tapespeed.setItemText(1, _translate("MainWindow", "3.75 ips"))
        self.analog_tapespeed.setItemText(2, _translate("MainWindow", "1.875 ips"))
        self.analog_tapespeed.setItemText(3, _translate("MainWindow", "15 ips"))
        self.analog_tracklayout_2.setItemText(0, _translate("MainWindow", "30 minute"))
        self.analog_tracklayout_2.setItemText(1, _translate("MainWindow", "60 minute"))
        self.analog_tracklayout_2.setItemText(2, _translate("MainWindow", "90 minute"))
        self.analog_tracklayout_2.setItemText(3, _translate("MainWindow", "120 minute"))
        self.analog_tracklayout_3.setItemText(0, _translate("MainWindow", "Normal bias"))
        self.analog_tracklayout_3.setItemText(1, _translate("MainWindow", "CrO2 bias"))
        self.analog_tracklayout_3.setItemText(2, _translate("MainWindow", "Metal bias"))
        self.analog_tracklayout_4.setItemText(0, _translate("MainWindow", "No Dolby EQ"))
        self.analog_tracklayout_4.setItemText(1, _translate("MainWindow", "Dolby B"))
        self.analog_tracklayout_4.setItemText(2, _translate("MainWindow", "Dolby C"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.analogInst), _translate("MainWindow", "Analog Instantiation"))
        self.toolButton_10.setText(_translate("MainWindow", "Add"))
        self.toolButton_9.setText(_translate("MainWindow", "Remove"))
        self.digitalinstantiation_upbutton.setText(_translate("MainWindow", "↑"))
        self.digitalinstantiation_downbutton.setText(_translate("MainWindow", "↓"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.digitalInst), _translate("MainWindow", "Digital Instantiations"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionNew.setText(_translate("MainWindow", "New..."))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as..."))
        self.actionBlow_away.setText(_translate("MainWindow", "Blow away..."))
        self.actionFoot.setText(_translate("MainWindow", "Foot"))
        self.actionHead.setText(_translate("MainWindow", "Head"))
        self.actionFingers.setText(_translate("MainWindow", "Fingers"))
        self.actionFoo.setText(_translate("MainWindow", "Foo"))
        self.actionBar.setText(_translate("MainWindow", "Bar"))

