# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Wed Nov  4 20:38:13 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1066, 740)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.layoutWidget = QtGui.QWidget(self.centralWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 1001, 25))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.resourceIdForm = QtGui.QFormLayout()
        self.resourceIdForm.setObjectName(_fromUtf8("resourceIdForm"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setMinimumSize(QtCore.QSize(59, 0))
        self.label.setObjectName(_fromUtf8("label"))
        self.resourceIdForm.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.resource_id = QtGui.QLineEdit(self.layoutWidget)
        self.resource_id.setMinimumSize(QtCore.QSize(200, 0))
        self.resource_id.setObjectName(_fromUtf8("resource_id"))
        self.resourceIdForm.setWidget(0, QtGui.QFormLayout.FieldRole, self.resource_id)
        self.horizontalLayout.addLayout(self.resourceIdForm)
        self.resourceTitleForm = QtGui.QFormLayout()
        self.resourceTitleForm.setObjectName(_fromUtf8("resourceTitleForm"))
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(59, 0))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.resourceTitleForm.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.resource_title = QtGui.QLineEdit(self.layoutWidget)
        self.resource_title.setMinimumSize(QtCore.QSize(200, 0))
        self.resource_title.setObjectName(_fromUtf8("resource_title"))
        self.resourceTitleForm.setWidget(0, QtGui.QFormLayout.FieldRole, self.resource_title)
        self.horizontalLayout.addLayout(self.resourceTitleForm)
        self.groupBox = QtGui.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(290, 50, 381, 621))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.layoutWidget1 = QtGui.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 30, 361, 581))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_4 = QtGui.QLabel(self.layoutWidget1)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_3.addWidget(self.label_4)
        self.analog_id = QtGui.QLineEdit(self.layoutWidget1)
        self.analog_id.setObjectName(_fromUtf8("analog_id"))
        self.verticalLayout_3.addWidget(self.analog_id)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_5 = QtGui.QLabel(self.layoutWidget1)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_6.addWidget(self.label_5)
        self.analog_source = QtGui.QLineEdit(self.layoutWidget1)
        self.analog_source.setObjectName(_fromUtf8("analog_source"))
        self.verticalLayout_6.addWidget(self.analog_source)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.verticalLayout_10.addLayout(self.horizontalLayout_5)
        self.tape_type = QtGui.QComboBox(self.layoutWidget1)
        self.tape_type.setObjectName(_fromUtf8("tape_type"))
        self.tape_type.addItem(_fromUtf8(""))
        self.tape_type.addItem(_fromUtf8(""))
        self.tape_type.addItem(_fromUtf8(""))
        self.verticalLayout_10.addWidget(self.tape_type)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_8 = QtGui.QLabel(self.layoutWidget1)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_7.addWidget(self.label_8)
        self.analog_location = QtGui.QLineEdit(self.layoutWidget1)
        self.analog_location.setObjectName(_fromUtf8("analog_location"))
        self.verticalLayout_7.addWidget(self.analog_location)
        self.horizontalLayout_6.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_9 = QtGui.QLabel(self.layoutWidget1)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_8.addWidget(self.label_9)
        self.analog_date = QtGui.QLineEdit(self.layoutWidget1)
        self.analog_date.setObjectName(_fromUtf8("analog_date"))
        self.verticalLayout_8.addWidget(self.analog_date)
        self.horizontalLayout_6.addLayout(self.verticalLayout_8)
        self.verticalLayout_10.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.analog_generation = QtGui.QComboBox(self.layoutWidget1)
        self.analog_generation.setObjectName(_fromUtf8("analog_generation"))
        self.analog_generation.addItem(_fromUtf8(""))
        self.analog_generation.addItem(_fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.analog_generation)
        self.analog_tapespeed = QtGui.QComboBox(self.layoutWidget1)
        self.analog_tapespeed.setObjectName(_fromUtf8("analog_tapespeed"))
        self.analog_tapespeed.addItem(_fromUtf8(""))
        self.analog_tapespeed.addItem(_fromUtf8(""))
        self.analog_tapespeed.addItem(_fromUtf8(""))
        self.analog_tapespeed.addItem(_fromUtf8(""))
        self.analog_tapespeed.addItem(_fromUtf8(""))
        self.analog_tapespeed.setItemText(4, _fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.analog_tapespeed)
        self.verticalLayout_10.addLayout(self.horizontalLayout_7)
        self.analog_tracklayout = QtGui.QComboBox(self.layoutWidget1)
        self.analog_tracklayout.setObjectName(_fromUtf8("analog_tracklayout"))
        self.analog_tracklayout.addItem(_fromUtf8(""))
        self.analog_tracklayout.addItem(_fromUtf8(""))
        self.analog_tracklayout.addItem(_fromUtf8(""))
        self.analog_tracklayout.addItem(_fromUtf8(""))
        self.analog_tracklayout.addItem(_fromUtf8(""))
        self.analog_tracklayout.addItem(_fromUtf8(""))
        self.analog_tracklayout.setItemText(5, _fromUtf8(""))
        self.verticalLayout_10.addWidget(self.analog_tracklayout)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_10 = QtGui.QLabel(self.layoutWidget1)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_9.addWidget(self.label_10)
        self.analog_premis_list = QtGui.QListWidget(self.layoutWidget1)
        self.analog_premis_list.setObjectName(_fromUtf8("analog_premis_list"))
        self.verticalLayout_9.addWidget(self.analog_premis_list)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.analogpremis_plusbutton = QtGui.QPushButton(self.layoutWidget1)
        self.analogpremis_plusbutton.setObjectName(_fromUtf8("analogpremis_plusbutton"))
        self.horizontalLayout_8.addWidget(self.analogpremis_plusbutton)
        self.analogpremis_minusbutton = QtGui.QPushButton(self.layoutWidget1)
        self.analogpremis_minusbutton.setEnabled(False)
        self.analogpremis_minusbutton.setObjectName(_fromUtf8("analogpremis_minusbutton"))
        self.horizontalLayout_8.addWidget(self.analogpremis_minusbutton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.analogpremis_upbutton = QtGui.QPushButton(self.layoutWidget1)
        self.analogpremis_upbutton.setEnabled(False)
        self.analogpremis_upbutton.setObjectName(_fromUtf8("analogpremis_upbutton"))
        self.horizontalLayout_8.addWidget(self.analogpremis_upbutton)
        self.analogpremis_downbutton = QtGui.QPushButton(self.layoutWidget1)
        self.analogpremis_downbutton.setEnabled(False)
        self.analogpremis_downbutton.setObjectName(_fromUtf8("analogpremis_downbutton"))
        self.horizontalLayout_8.addWidget(self.analogpremis_downbutton)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.groupBox_2 = QtGui.QGroupBox(self.centralWidget)
        self.groupBox_2.setGeometry(QtCore.QRect(680, 50, 381, 621))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.layoutWidget_7 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget_7.setGeometry(QtCore.QRect(10, 30, 361, 581))
        self.layoutWidget_7.setObjectName(_fromUtf8("layoutWidget_7"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.layoutWidget_7)
        self.verticalLayout_11.setMargin(0)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.digitalinstantiation_list = QtGui.QListWidget(self.layoutWidget_7)
        self.digitalinstantiation_list.setObjectName(_fromUtf8("digitalinstantiation_list"))
        self.verticalLayout_16.addWidget(self.digitalinstantiation_list)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.digitalinstantiation_plusbutton = QtGui.QPushButton(self.layoutWidget_7)
        self.digitalinstantiation_plusbutton.setObjectName(_fromUtf8("digitalinstantiation_plusbutton"))
        self.horizontalLayout_12.addWidget(self.digitalinstantiation_plusbutton)
        self.digitalinstantiation_minusbutton = QtGui.QPushButton(self.layoutWidget_7)
        self.digitalinstantiation_minusbutton.setEnabled(False)
        self.digitalinstantiation_minusbutton.setObjectName(_fromUtf8("digitalinstantiation_minusbutton"))
        self.horizontalLayout_12.addWidget(self.digitalinstantiation_minusbutton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem1)
        self.digitalinstantiation_upbutton = QtGui.QPushButton(self.layoutWidget_7)
        self.digitalinstantiation_upbutton.setEnabled(False)
        self.digitalinstantiation_upbutton.setObjectName(_fromUtf8("digitalinstantiation_upbutton"))
        self.horizontalLayout_12.addWidget(self.digitalinstantiation_upbutton)
        self.digitalinstantiation_downbutton = QtGui.QPushButton(self.layoutWidget_7)
        self.digitalinstantiation_downbutton.setEnabled(False)
        self.digitalinstantiation_downbutton.setObjectName(_fromUtf8("digitalinstantiation_downbutton"))
        self.horizontalLayout_12.addWidget(self.digitalinstantiation_downbutton)
        self.verticalLayout_16.addLayout(self.horizontalLayout_12)
        self.verticalLayout_11.addLayout(self.verticalLayout_16)
        self.layoutWidget2 = QtGui.QWidget(self.centralWidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 50, 266, 621))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_3 = QtGui.QLabel(self.layoutWidget2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.description_list = QtGui.QListWidget(self.layoutWidget2)
        self.description_list.setObjectName(_fromUtf8("description_list"))
        self.verticalLayout.addWidget(self.description_list)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.descriptionlist_plusbutton = QtGui.QPushButton(self.layoutWidget2)
        self.descriptionlist_plusbutton.setEnabled(True)
        self.descriptionlist_plusbutton.setObjectName(_fromUtf8("descriptionlist_plusbutton"))
        self.horizontalLayout_2.addWidget(self.descriptionlist_plusbutton)
        self.descriptionlist_minusbutton = QtGui.QPushButton(self.layoutWidget2)
        self.descriptionlist_minusbutton.setEnabled(False)
        self.descriptionlist_minusbutton.setObjectName(_fromUtf8("descriptionlist_minusbutton"))
        self.horizontalLayout_2.addWidget(self.descriptionlist_minusbutton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.descriptionlist_upbutton = QtGui.QPushButton(self.layoutWidget2)
        self.descriptionlist_upbutton.setEnabled(False)
        self.descriptionlist_upbutton.setObjectName(_fromUtf8("descriptionlist_upbutton"))
        self.horizontalLayout_2.addWidget(self.descriptionlist_upbutton)
        self.descriptionlist_downbutton = QtGui.QPushButton(self.layoutWidget2)
        self.descriptionlist_downbutton.setEnabled(False)
        self.descriptionlist_downbutton.setObjectName(_fromUtf8("descriptionlist_downbutton"))
        self.horizontalLayout_2.addWidget(self.descriptionlist_downbutton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_6 = QtGui.QLabel(self.layoutWidget2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_4.addWidget(self.label_6)
        self.contributor_list = QtGui.QListWidget(self.layoutWidget2)
        self.contributor_list.setObjectName(_fromUtf8("contributor_list"))
        self.verticalLayout_4.addWidget(self.contributor_list)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.contributorlist_plusbutton = QtGui.QPushButton(self.layoutWidget2)
        self.contributorlist_plusbutton.setObjectName(_fromUtf8("contributorlist_plusbutton"))
        self.horizontalLayout_3.addWidget(self.contributorlist_plusbutton)
        self.contributorlist_minusbutton = QtGui.QPushButton(self.layoutWidget2)
        self.contributorlist_minusbutton.setEnabled(False)
        self.contributorlist_minusbutton.setObjectName(_fromUtf8("contributorlist_minusbutton"))
        self.horizontalLayout_3.addWidget(self.contributorlist_minusbutton)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.contributorlist_upbutton = QtGui.QPushButton(self.layoutWidget2)
        self.contributorlist_upbutton.setEnabled(False)
        self.contributorlist_upbutton.setObjectName(_fromUtf8("contributorlist_upbutton"))
        self.horizontalLayout_3.addWidget(self.contributorlist_upbutton)
        self.contributorlist_downbutton = QtGui.QPushButton(self.layoutWidget2)
        self.contributorlist_downbutton.setEnabled(False)
        self.contributorlist_downbutton.setObjectName(_fromUtf8("contributorlist_downbutton"))
        self.horizontalLayout_3.addWidget(self.contributorlist_downbutton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_7 = QtGui.QLabel(self.layoutWidget2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_5.addWidget(self.label_7)
        self.language_list = QtGui.QListWidget(self.layoutWidget2)
        self.language_list.setObjectName(_fromUtf8("language_list"))
        self.verticalLayout_5.addWidget(self.language_list)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.languagelist_plusbutton = QtGui.QPushButton(self.layoutWidget2)
        self.languagelist_plusbutton.setObjectName(_fromUtf8("languagelist_plusbutton"))
        self.horizontalLayout_4.addWidget(self.languagelist_plusbutton)
        self.languagelist_minusbutton = QtGui.QPushButton(self.layoutWidget2)
        self.languagelist_minusbutton.setEnabled(False)
        self.languagelist_minusbutton.setObjectName(_fromUtf8("languagelist_minusbutton"))
        self.horizontalLayout_4.addWidget(self.languagelist_minusbutton)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.languagelist_upbutton = QtGui.QPushButton(self.layoutWidget2)
        self.languagelist_upbutton.setEnabled(False)
        self.languagelist_upbutton.setObjectName(_fromUtf8("languagelist_upbutton"))
        self.horizontalLayout_4.addWidget(self.languagelist_upbutton)
        self.languagelist_downbutton = QtGui.QPushButton(self.layoutWidget2)
        self.languagelist_downbutton.setEnabled(False)
        self.languagelist_downbutton.setObjectName(_fromUtf8("languagelist_downbutton"))
        self.horizontalLayout_4.addWidget(self.languagelist_downbutton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addLayout(self.verticalLayout_5)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1066, 22))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionSave_as = QtGui.QAction(MainWindow)
        self.actionSave_as.setObjectName(_fromUtf8("actionSave_as"))
        self.actionBlow_away = QtGui.QAction(MainWindow)
        self.actionBlow_away.setObjectName(_fromUtf8("actionBlow_away"))
        self.actionFoot = QtGui.QAction(MainWindow)
        self.actionFoot.setObjectName(_fromUtf8("actionFoot"))
        self.actionHead = QtGui.QAction(MainWindow)
        self.actionHead.setObjectName(_fromUtf8("actionHead"))
        self.actionFingers = QtGui.QAction(MainWindow)
        self.actionFingers.setObjectName(_fromUtf8("actionFingers"))
        self.actionFoo = QtGui.QAction(MainWindow)
        self.actionFoo.setObjectName(_fromUtf8("actionFoo"))
        self.actionBar = QtGui.QAction(MainWindow)
        self.actionBar.setObjectName(_fromUtf8("actionBar"))
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "PBCore Editor", None))
        self.label.setText(_translate("MainWindow", "Resource ID:", None))
        self.label_2.setText(_translate("MainWindow", "Resource Title:", None))
        self.groupBox.setTitle(_translate("MainWindow", "Analog instantiation", None))
        self.label_4.setText(_translate("MainWindow", "Identifier:", None))
        self.label_5.setText(_translate("MainWindow", "Source:", None))
        self.tape_type.setItemText(0, _translate("MainWindow", "1/4\" audio tape", None))
        self.tape_type.setItemText(1, _translate("MainWindow", "Cassette tape", None))
        self.tape_type.setItemText(2, _translate("MainWindow", "Microcassette", None))
        self.label_8.setText(_translate("MainWindow", "Location:", None))
        self.label_9.setText(_translate("MainWindow", "Date:", None))
        self.analog_generation.setItemText(0, _translate("MainWindow", "Original", None))
        self.analog_generation.setItemText(1, _translate("MainWindow", "Copy", None))
        self.analog_tapespeed.setItemText(0, _translate("MainWindow", "7.5 ips", None))
        self.analog_tapespeed.setItemText(1, _translate("MainWindow", "3.75 ips", None))
        self.analog_tapespeed.setItemText(2, _translate("MainWindow", "1.875 ips", None))
        self.analog_tapespeed.setItemText(3, _translate("MainWindow", "15 ips", None))
        self.analog_tracklayout.setItemText(0, _translate("MainWindow", "Half-track stereo", None))
        self.analog_tracklayout.setItemText(1, _translate("MainWindow", "Half-track mono", None))
        self.analog_tracklayout.setItemText(2, _translate("MainWindow", "Full-track mono", None))
        self.analog_tracklayout.setItemText(3, _translate("MainWindow", "Quarter-track stereo", None))
        self.analog_tracklayout.setItemText(4, _translate("MainWindow", "Four-track", None))
        self.label_10.setText(_translate("MainWindow", "Analog instantiation PREMIS event(s):", None))
        self.analogpremis_plusbutton.setText(_translate("MainWindow", "+", None))
        self.analogpremis_minusbutton.setText(_translate("MainWindow", "–", None))
        self.analogpremis_upbutton.setText(_translate("MainWindow", "↑", None))
        self.analogpremis_downbutton.setText(_translate("MainWindow", "↓", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Digital instantiations", None))
        self.digitalinstantiation_plusbutton.setText(_translate("MainWindow", "+", None))
        self.digitalinstantiation_minusbutton.setText(_translate("MainWindow", "–", None))
        self.digitalinstantiation_upbutton.setText(_translate("MainWindow", "↑", None))
        self.digitalinstantiation_downbutton.setText(_translate("MainWindow", "↓", None))
        self.label_3.setText(_translate("MainWindow", "Description(s):", None))
        self.descriptionlist_plusbutton.setText(_translate("MainWindow", "+", None))
        self.descriptionlist_minusbutton.setText(_translate("MainWindow", "–", None))
        self.descriptionlist_upbutton.setText(_translate("MainWindow", "↑", None))
        self.descriptionlist_downbutton.setText(_translate("MainWindow", "↓", None))
        self.label_6.setText(_translate("MainWindow", "Contributor(s):", None))
        self.contributorlist_plusbutton.setText(_translate("MainWindow", "+", None))
        self.contributorlist_minusbutton.setText(_translate("MainWindow", "–", None))
        self.contributorlist_upbutton.setText(_translate("MainWindow", "↑", None))
        self.contributorlist_downbutton.setText(_translate("MainWindow", "↓", None))
        self.label_7.setText(_translate("MainWindow", "Language(s):", None))
        self.languagelist_plusbutton.setText(_translate("MainWindow", "+", None))
        self.languagelist_minusbutton.setText(_translate("MainWindow", "–", None))
        self.languagelist_upbutton.setText(_translate("MainWindow", "↑", None))
        self.languagelist_downbutton.setText(_translate("MainWindow", "↓", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionNew.setText(_translate("MainWindow", "New...", None))
        self.actionOpen.setText(_translate("MainWindow", "Open...", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionClose.setText(_translate("MainWindow", "Close", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionSave_as.setText(_translate("MainWindow", "Save as...", None))
        self.actionBlow_away.setText(_translate("MainWindow", "Blow away...", None))
        self.actionFoot.setText(_translate("MainWindow", "Foot", None))
        self.actionHead.setText(_translate("MainWindow", "Head", None))
        self.actionFingers.setText(_translate("MainWindow", "Fingers", None))
        self.actionFoo.setText(_translate("MainWindow", "Foo", None))
        self.actionBar.setText(_translate("MainWindow", "Bar", None))

